# -------=======------- Additions API by chrismin13 -------=======------- #
# -------=======----- Resource Pack Combiner by fihgu -----=======------- #
# = #
# -------=======-------====== Configuration File =====-------=======------- #
# -----=======-------=======-------=======-------=======-------=======----- #
# = #
# # enable-debug: For developers or debugging only. Valid values are false,
# #               true, and super. Super mode will be extremely detailed and
# #               will automatically regenerate the Resource Pack on launch.
# = #
# ------=======-------=======-------=======-------=======-------=======----- #
# = #
# HTTP: 
# # Recommended to leave as default, apart from the following values.
# # localhost: This is picked automatically by default so it does not appear.
# #            However, if you are having issues with the texture pack, try
# #            adding this entry and setting it to 0.0.0.0.
# # port:The Port you specify must be open and not in use from anything else
# #      in your network. Common ports on shared hosting machines are most
# #      from 8123 and above as 8123 is used by the popular plugin DynMap.
# #      If unsure about this, ask your hosting provider for more info. 
# = #
# ------=======-------=======-------=======-------=======-------=======----- #
# = #
# Resource Pack:
# # send-to-player: Whether the player will receive the Resource Pack when
# #                 they join the server. 
# # force-on-join: Whether the players will be kicked if they do not
# #                accept the Resource Pack. Default is true.
# # overwrite-files: Whether a file will be overwritten while merging
# #                  resource packs. Default is true.
# # smooth-leather-armor-texture: Whether the Smooth  Leather Armor
# #                               Resource Pack will be loaded or not.
# #                               Default is true.
# = #
# ------=======-------=======-------=======-------=======-------=======----- #
# = #
# BossBar:
# # show: Whether the Durability Boss Bar will be enabled. Default is true.
# # vanilla-items: Whether the Durability Boss Bar will display durability
# #                for items that are already in the game. Default is true.
# # custom-items: Whether the Durability Boss Bar will display durability
# #               for custom items from the Additions API. Default is true.
# = #
# ------=======-------=======-------=======-------=======-------=======----- #

enable-debug: false

http:
 localhost:
 port: 8125
 host: 
 numReadThread: 4
 numWriteThread: 4
 
resource-pack:
 send-to-player: true
 force-on-join: true
 overwrite-files: true
 smooth-leather-armor-texture: true
 
bossbar:
 show: true
 vanilla-items: true
 custom-items: true